server:
    port: 6969
    webroot: 'ui'
    origins: []
videoCacheTime: 30
youtube:
    apikey: ''
    uploadPlaylistID: ''
sql:
    driver: 'mysql'
    host: 'localhost'
    port: 8006
    name: 'test'
    user: 'root'
    password: ''
